name: CD

on:
  push:
    branches:
      - main
    
jobs:
  hosting:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup git
      run: |
        git config --global user.name 'DAEUN28'
        git config --global user.email 'acone1128@gmail.com'
        git config pull.rebase false
        git pull origin hosting
        git checkout -t origin/hosting
        git merge main
    - name: grant sudo permission
      run: chmod 777 hosting.sh
    - name: update hosting files
      run: sh hosting.sh
    - name: git commit & push
      run: |
        git add -A
        git commit -m "Updated: `date +'%Y-%m-%d %H:%M:%S'`"
        git push
